"use client";
import { useRef, useState } from "react";
import { countries, localSites, perspectives, services } from "./data";
import es from "./translations/es.json";
import en from "./translations/en.json";
import pt from "./translations/pt.json";
import localTranslations from "./translations/local-sites.json";

export type PageKey = "global"|"mexico"|"salvador";
export type Locale = "es"|"en"|"pt";
const catalogs={es,en,pt} as const;
const ui={es:{nav:["El Consorcio","Red Global","Especialidades","Perspectivas","Contacto"],language:"Español",contact:{label:"CONTACTO",title:"Hablemos de su próximo desafío.",intro:"Nuestro equipo internacional coordina necesidades de auditoría, impuestos, consultoría y outsourcing para acompañarle en cada etapa de su crecimiento.",direct:"Contacto directo",email:"Correo",phone:"Teléfono",office:"Oficina",form:"Cuéntenos cómo podemos ayudarle",name:"Nombre",company:"Empresa",mail:"Correo electrónico",tel:"Teléfono",message:"Mensaje",send:"Preparar correo",follow:"Síganos"}},en:{nav:["The Consortium","Global Network","Specialties","Insights","Contact"],language:"English",contact:{label:"CONTACT",title:"Let’s discuss your next challenge.",intro:"Our international team coordinates audit, tax, consulting and outsourcing needs to support every stage of your growth.",direct:"Direct contact",email:"Email",phone:"Phone",office:"Office",form:"Tell us how we can help",name:"Name",company:"Company",mail:"Email address",tel:"Phone",message:"Message",send:"Prepare email",follow:"Follow us"}},pt:{nav:["O Consórcio","Rede Global","Especialidades","Perspectivas","Contato"],language:"Português",contact:{label:"CONTATO",title:"Vamos conversar sobre seu próximo desafio.",intro:"Nossa equipe internacional coordena necessidades de auditoria, impostos, consultoria e outsourcing para apoiar cada etapa do seu crescimento.",direct:"Contato direto",email:"E-mail",phone:"Telefone",office:"Escritório",form:"Conte-nos como podemos ajudar",name:"Nome",company:"Empresa",mail:"E-mail",tel:"Telefone",message:"Mensagem",send:"Preparar e-mail",follow:"Siga-nos"}}} as const;

export function Brand({inverse=false}:{inverse?:boolean}){return <span className={inverse?"brand inverse":"brand"}><b>Audit</b><i>axes</i><svg className="globe" viewBox="0 0 36 36" aria-hidden="true"><circle cx="18" cy="18" r="15.5" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M7 13.5 11 10l4 1 1.5 3.5-2 3.5 3 2.5-1 4-4 1-2.5-3-3-1M20 4l3 4 4 .5 2 3.5-3.5 2-1 3-3.5 1-2-4 1-3-2.5-2L20 4ZM23 21l4-2 3 2-1 5-4 3-4-2Z" fill="currentColor" opacity=".9"/></svg></span>}

export function NetworkBackground(){return <div className="network-background" aria-hidden="true"><svg viewBox="0 0 1000 700" preserveAspectRatio="none"><g className="network-lines"><path d="M55 125 210 245 360 145 520 280 700 180 890 300"/><path d="M110 520 280 390 455 505 610 390 820 530 950 420"/><path d="M210 245 280 390M360 145 455 505M520 280 610 390M700 180 820 530"/></g><g className="network-nodes"><circle cx="55" cy="125" r="3"/><circle cx="210" cy="245" r="4"/><circle cx="360" cy="145" r="3"/><circle cx="520" cy="280" r="4"/><circle cx="700" cy="180" r="3"/><circle cx="890" cy="300" r="4"/><circle cx="110" cy="520" r="3"/><circle cx="280" cy="390" r="4"/><circle cx="455" cy="505" r="3"/><circle cx="610" cy="390" r="4"/><circle cx="820" cy="530" r="3"/><circle cx="950" cy="420" r="4"/></g></svg></div>}

function FlagIcon({locale}:{locale:Locale}){return <svg className="flag-icon" viewBox="0 0 28 20" aria-hidden="true">{locale==="es"&&<><rect width="28" height="20" rx="2" fill="#AA151B"/><rect y="5" width="28" height="10" fill="#F1BF00"/><rect x="8" y="8" width="2.5" height="4" rx=".4" fill="#AA151B"/></>}{locale==="pt"&&<><rect width="28" height="20" rx="2" fill="#046A38"/><rect x="11" width="17" height="20" rx="2" fill="#DA291C"/><circle cx="11" cy="10" r="4.5" fill="#FFCD00"/><circle cx="11" cy="10" r="3.2" fill="#fff"/><circle cx="11" cy="10" r="2.8" fill="#1F4E79"/></>}{locale==="en"&&<><rect width="28" height="20" rx="2" fill="#012169"/><path d="M0 0 28 20M28 0 0 20" stroke="#fff" strokeWidth="5"/><path d="M0 0 28 20M28 0 0 20" stroke="#C8102E" strokeWidth="2"/><path d="M14 0v20M0 10h28" stroke="#fff" strokeWidth="6"/><path d="M14 0v20M0 10h28" stroke="#C8102E" strokeWidth="3"/></>}</svg>}

export function ProposalSelector({proposal,locale,onChange}:{proposal:number,locale:Locale,onChange:(n:number)=>void}){
  const label={es:"Propuesta",en:"Design",pt:"Proposta"}[locale];return <aside className="proposal-switcher" aria-label={label}><span>{label}</span>{[1,2,3].map(n=><button key={n} className={proposal===n?"active":""} onClick={()=>onChange(n)} aria-label={`${label} ${n}`}>0{n}</button>)}</aside>
}

export function Header({proposal,page,locale,onLocale,onPage}:{proposal:number,page:PageKey,locale:Locale,onLocale:(l:Locale)=>void,onPage:(p:PageKey)=>void}){
  const [menuOpen,setMenuOpen]=useState(false);
  const globalSections=["consorcio","red","servicios","perspectivas","contacto"].map((id,i)=>[id,ui[locale].nav[i]] as const);
  const localSections={es:[["firma","La Firma"],["metodo","Nuestro Método"],["capacidades","Capacidades"],["equipo","Nuestro Equipo"],["contacto","Contacto"]],en:[["firma","The Firm"],["metodo","Our Method"],["capacidades","Capabilities"],["equipo","Our Team"],["contacto","Contact"]],pt:[["firma","A Firma"],["metodo","Nosso Método"],["capacidades","Capacidades"],["equipo","Nossa Equipe"],["contacto","Contato"]]}[locale] as readonly (readonly [string,string])[];
  const sections=page==="global"?globalSections:localSections;
  const country=page==="mexico"?{es:"México",en:"Mexico",pt:"México"}[locale]:page==="salvador"?"El Salvador":"";
  const globalLabel={es:"Volver a Global",en:"Back to Global",pt:"Voltar ao Global"}[locale];
  const go=(id:string)=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
  return <header className="site-header original-banner"><div className="header-identity"><button className="brand-button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><Brand/>{country&&<span className="country-name"><i/> {country}</span>}</button></div><button className={menuOpen?"mobile-menu-button active":"mobile-menu-button"} aria-label={menuOpen?"Cerrar menú":"Abrir menú"} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><span/><span/><span/></button><nav className={menuOpen?"section-navigation open":"section-navigation"} aria-label="Secciones de AUDITAXES">{page!=="global"&&<button className="global-return" onClick={()=>{setMenuOpen(false);onPage("global")}}>← {globalLabel}</button>}{sections.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</nav><details className="language-menu"><summary className="language-pill"><FlagIcon locale={locale}/><b>{ui[locale].language}</b><span>⌄</span></summary><div>{(["es","en","pt"] as Locale[]).map(l=><button key={l} className={locale===l?"active":""} onClick={e=>{onLocale(l);(e.currentTarget.closest("details") as HTMLDetailsElement)?.removeAttribute("open")}}><FlagIcon locale={l}/><span>{l==="es"?"Español":l==="en"?"English":"Português"}</span></button>)}</div></details></header>
}

export function WorldMap({locale,onPage}:{locale:Locale,onPage:(p:PageKey)=>void}){
  const [selected,setSelected]=useState(0); const [modal,setModal]=useState(false); const [globalView,setGlobalView]=useState(false); const [drag,setDrag]=useState({x:0,y:0}); const [dragging,setDragging]=useState(false); const dragStart=useRef({x:0,y:0,baseX:0,baseY:0}); const country=countries[selected];const c=catalogs[locale];const countryName=(item:typeof countries[number])=>c.countries[item[0] as keyof typeof c.countries];const mapText={es:{global:"Ver mapa global",back:"Volver a",visit:"Visitar sitio",status:"Ver estado",active:"Sede activa",planned:"Próxima sede",building:"Sitio en construcción",buildingBody:"Esta sede estará disponible próximamente."},en:{global:"View global map",back:"Back to",visit:"Visit site",status:"View status",active:"Active office",planned:"Planned office",building:"Site under construction",buildingBody:"This office will be available soon."},pt:{global:"Ver mapa global",back:"Voltar para",visit:"Visitar site",status:"Ver status",active:"Escritório ativo",planned:"Próximo escritório",building:"Site em construção",buildingBody:"Este escritório estará disponível em breve."}}[locale];
  const pointFor=(c:typeof countries[number]):[number,number]=>[((c[3]+180)/360)*100,((90-c[2])/180)*100];
  const [x,y]=pointFor(country);
  const zoomByCountry:Record<string,number>={"mexico":3.6,"guatemala":4.8,"el-salvador":5.2,"costa-rica":4.8,"panama":4.7,"belize":5,"colombia":3.8,"peru":3.6,"argentina":3.6,"dominican-republic":4.8,"venezuela":3.7,"united-kingdom":3.8,"ecuador":4.1,"uruguay":4,"spain":4,"albania":4.2,"cyprus":4.3,"egypt":4,"france":4,"united-states":3.6,"nicaragua":5,"jamaica":5,"saint-kitts":5.2,"dominica":5.2,"grenada":5.2,"saint-vincent":5.2};
  const zoom=zoomByCountry[country[0]]??3.8;
  const distance=(a:typeof countries[number],b:typeof countries[number])=>{const rad=Math.PI/180;const dLat=(b[2]-a[2])*rad,dLon=(b[3]-a[3])*rad;const v=Math.sin(dLat/2)**2+Math.cos(a[2]*rad)*Math.cos(b[2]*rad)*Math.sin(dLon/2)**2;return 2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
  const ranked=countries.map((c,i)=>({c,i,d:distance(country,c)})).filter(v=>v.i!==selected).sort((a,b)=>a.d-b.d);
  const connections=[...ranked.slice(0,3).map(v=>({...v,kind:"near"})),{...ranked[ranked.length-1],kind:"far"}];
  const choose=(i:number)=>{setSelected(i);setGlobalView(false);setDrag({x:0,y:0});setModal(false)};
  const startDrag=(e:React.PointerEvent<HTMLDivElement>)=>{if((e.target as HTMLElement).closest("button"))return;setDragging(true);dragStart.current={x:e.clientX,y:e.clientY,baseX:drag.x,baseY:drag.y};e.currentTarget.setPointerCapture(e.pointerId)};
  const moveDrag=(e:React.PointerEvent<HTMLDivElement>)=>{if(!dragging)return;const limitX=e.currentTarget.clientWidth*.45,limitY=e.currentTarget.clientHeight*.45;setDrag({x:Math.max(-limitX,Math.min(limitX,dragStart.current.baseX+e.clientX-dragStart.current.x)),y:Math.max(-limitY,Math.min(limitY,dragStart.current.baseY+e.clientY-dragStart.current.y))})};
  const endDrag=(e:React.PointerEvent<HTMLDivElement>)=>{if(!dragging)return;setDragging(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
  const go=()=>{if(country[4]) onPage(country[0]==="mexico"?"mexico":"salvador"); else setModal(true)};
  return <section className="world-map" id="red"><div className="map-heading"><p className="section-label">{c.nav.network}</p><h2>{c.home.networkTitle}</h2><p>{c.home.networkBody}</p></div><div className="map-layout"><div className="location-list"><span>{c.common.allLocations}</span>{countries.map((item,i)=><button key={item[0]} onClick={()=>choose(i)} className={i===selected?"selected":""}><i className={item[4]?"live":""}/>{countryName(item)}<small>{item[4]?c.common.active:c.common.soon}</small></button>)}</div><div className={["map-canvas",globalView?"is-global":"is-focused",dragging?"is-dragging":""].filter(Boolean).join(" ")} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><button className="global-map-button" onClick={()=>{setGlobalView(v=>!v);setDrag({x:0,y:0})}}>{globalView?`${mapText.back} ${countryName(country)}`:mapText.global}<span>↗</span></button><div key={globalView?"global":country[0]} className="map-stage" style={{"--focus-x":globalView?"50%":`${x}%`,"--focus-y":globalView?"50%":`${y}%`,"--pan-x":globalView?"-50%":`${-x}%`,"--pan-y":globalView?"-50%":`${-y}%`,"--zoom":globalView?1:zoom,"--node-scale":1/(globalView?1:zoom),"--drag-x":`${drag.x}px`,"--drag-y":`${drag.y}px`} as React.CSSProperties}><img src="/world-map.svg" alt="" draggable="false"/><svg key={country[0]} className="map-connections" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{connections.map(({c:item,kind})=>{const [tx,ty]=pointFor(item);const mx=(x+tx)/2,curve=(kind==="far"?-1:1)*Math.min(8,Math.abs(tx-x)*.12+2);return <path key={`${country[0]}-${item[0]}`} className={kind} d={`M ${x} ${y} Q ${mx} ${(y+ty)/2-curve} ${tx} ${ty}`}/>})}</svg><span key={`focus-${country[0]}`} className="map-focus-cinematic" style={{left:`${x}%`,top:`${y}%`}} aria-hidden="true"/>{countries.map((item,i)=>{const [cx,cy]=pointFor(item);return <button key={item[0]} aria-label={countryName(item)} onClick={()=>choose(i)} className={["map-node",item[4]?"live":"",i===selected?"selected":""].filter(Boolean).join(" ")} style={{left:`${cx}%`,top:`${cy}%`}}/>})}</div><div key={`card-${country[0]}`} className="map-card"><small>{c.network.selectedLabel}</small><strong>{countryName(country)}</strong><span>{country[4]?mapText.active:mapText.planned}</span><button onClick={go}>{country[4]?mapText.visit:mapText.status} ↗</button></div></div></div>{modal&&<div className="modal" onClick={()=>setModal(false)}><div onClick={e=>e.stopPropagation()}><button onClick={()=>setModal(false)}>×</button><small>AUDITAXES Global</small><h3>{mapText.building}</h3><p>{mapText.buildingBody}</p></div></div>}</section>
}

function Footer({locale,onPage}:{locale:Locale,onPage:(p:PageKey)=>void}){const c=catalogs[locale];return <footer><div><Brand inverse/><p>{c.footer.tagline}</p></div><nav><strong>{c.footer.services}</strong><a href="#consorcio">{c.nav.consortium}</a><a href="#servicios">{c.nav.specialties}</a><a href="#perspectivas">{c.nav.perspectives}</a></nav><nav><strong>{c.footer.network}</strong><button onClick={()=>onPage("global")}>{c.nav.network}</button><button onClick={()=>onPage("mexico")}>{c.countries.mexico}</button><button onClick={()=>onPage("salvador")}>{c.countries["el-salvador"]}</button></nav><nav><strong>{c.nav.contact}</strong><a href="mailto:info@audit-taxes.com.mx">info@audit-taxes.com.mx</a><span>+52 55 1451 1169</span></nav><small>{c.footer.copyright}</small></footer>}

function SocialIcon({name}:{name:"facebook"|"instagram"|"linkedin"}){return <svg className={`social-icon ${name}`} viewBox="0 0 24 24" aria-hidden="true">{name==="facebook"&&<path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v8h4v-8h3l1-4h-4V9c0-.7.3-1 1-1Z"/>}{name==="instagram"&&<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" className="fill"/></>}{name==="linkedin"&&<><path d="M5 9v11M5 5.5v.1M10 20V9m0 5c0-3 7-4 7 1v5M17 20v-5"/></>}</svg>}

function ContactSection({locale,details}:{locale:Locale,details?:{email:string,phone:string,address:string}}){const t=ui[locale].contact;const email=details?.email??"info@audit-taxes.com.mx";const phone=details?.phone??"+52 55 5554 0921 · +52 55 1451 1169";const address=details?.address??"Corina 130, Del Carmen Coyoacán, CDMX";const whatsapp=phone.replace(/\D/g,"");const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=[t.name,t.company,t.mail,t.tel,t.message].map((label,i)=>`${label}: ${d.get(["name","company","email","phone","message"][i])||"—"}`).join("\n\n");location.href=`mailto:${email}?subject=${encodeURIComponent(t.title)}&body=${encodeURIComponent(body)}`};return <section className="contact-section" id="contacto"><header><p className="section-label">{t.label}</p><h2>{t.title}</h2><p>{t.intro}</p></header><div className="contact-experience"><aside><h3>{t.direct}</h3><a href={`mailto:${email}`}><b>✉</b><span><strong>{t.email}</strong><small>{email}</small></span></a><a href={`tel:${phone}`}><b>☎</b><span><strong>{t.phone}</strong><small>{phone}</small></span></a><a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><b>◉</b><span><strong>WhatsApp</strong><small>{phone}</small></span></a><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noreferrer"><b>⌖</b><span><strong>{t.office}</strong><small>{address}</small></span></a></aside><form onSubmit={submit}><h3>{t.form}</h3><label><span>{t.name}</span><input name="name" required/></label><label><span>{t.company}</span><input name="company"/></label><label><span>{t.mail}</span><input name="email" type="email" required/></label><label><span>{t.tel}</span><input name="phone" type="tel"/></label><label className="contact-message"><span>{t.message}</span><textarea name="message" rows={5} required/></label><button type="submit">{t.send}<span>↗</span></button></form></div><div className="contact-social"><span>{t.follow}</span><a href="https://www.facebook.com/people/Auditaxes/61569843038041/" target="_blank" rel="noreferrer" aria-label="Facebook"><SocialIcon name="facebook"/><b>Facebook</b></a><a href="https://www.instagram.com/auditaxes.mx/" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon name="instagram"/><b>Instagram</b></a><a href="https://www.linkedin.com/company/auditaxes/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><SocialIcon name="linkedin"/><b>LinkedIn</b></a></div></section>}

export function GlobalPage({proposal,locale,onPage}:{proposal:number,locale:Locale,onPage:(p:PageKey)=>void}){
 const c=catalogs[locale];const pillarBodies={es:["Metodologías consistentes, independencia profesional y atención precisa en cada entrega.","Equipos conectados que interpretan cada mercado sin perder la perspectiva internacional.","Acompañamiento cercano para comprender el negocio y anticipar sus próximos desafíos."],en:["Consistent methodologies, professional independence and precision in every deliverable.","Connected teams that understand each market without losing an international perspective.","Close support to understand the business and anticipate its next challenges."],pt:["Metodologias consistentes, independência profissional e precisão em cada entrega.","Equipes conectadas que interpretam cada mercado sem perder a perspectiva internacional.","Acompanhamento próximo para compreender o negócio e antecipar seus próximos desafios."]}[locale];const imageLabel={es:"Precisión en cada análisis",en:"Precision in every analysis",pt:"Precisão em cada análise"}[locale];return <><section className="global-hero"><div className="hero-copy"><p className="section-label">AUDITAXES GLOBAL</p><h1>{c.home.heroTitle}</h1><p>{c.home.heroBody}</p><a href="#red">{c.home.heroPrimary}<span>↗</span></a></div><div className="hero-media"><img src={proposal===2?"/images/office.jpg":"/images/architecture.jpg"} alt=""/><span>{locale==="es"?"Experiencia local":locale==="en"?"Local expertise":"Experiência local"}<br/><b>{locale==="es"?"Visión global":locale==="en"?"Global vision":"Visão global"}</b></span></div></section><section className="consortium" id="consorcio"><div><p className="section-label">{c.nav.consortium}</p><h2>{c.home.consortiumTitle}</h2></div><div><p>{c.home.consortiumBody}</p><ol>{c.home.pillars.map((p,i)=><li key={p.label}><span>0{i+1}</span><b>{p.label}</b><p>{pillarBodies[i]}</p></li>)}</ol></div></section><WorldMap locale={locale} onPage={onPage}/><section className="services" id="servicios"><div className="section-intro"><p className="section-label">{c.nav.specialties}</p><h2>{c.home.specialtiesTitle}</h2><p>{c.home.specialtiesBody}</p></div><div className="services-visual"><img src="/images/finance.jpg" alt=""/><span>{imageLabel}</span></div><div className="service-grid">{c.specialties.services.map(s=><article key={s.id}><h3>{s.title}</h3><p>{s.body}</p><ul>{s.details.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section><section className="perspectives" id="perspectivas"><div className="perspective-image"><img src="/images/meeting.jpg" alt=""/></div><div><p className="section-label">{c.nav.perspectives}</p><h2>{c.perspectives.title}</h2>{c.perspectives.topics.map((p,i)=><article key={p.title}><span>0{i+1} · {p.category}</span><h3>{p.title}</h3><p>{p.body}</p></article>)}</div></section><ContactSection locale={locale}/><Footer locale={locale} onPage={onPage}/></>
}

function LocalMethod({locale}:{locale:Locale}){const text={es:{label:"NUESTRO MÉTODO",title:"Claridad en cada etapa.",intro:"Un proceso común mantiene la conversación enfocada y convierte la complejidad en decisiones concretas.",phase:"Fase",steps:[["Comprender","Escuchamos el contexto, los objetivos y los riesgos particulares de su organización."],["Coordinar","Integramos las capacidades técnicas y territoriales adecuadas para cada proyecto."],["Resolver","Entregamos conclusiones accionables, documentación clara y seguimiento cercano."]]},en:{label:"OUR METHOD",title:"Clarity at every stage.",intro:"A shared process keeps the conversation focused and turns complexity into concrete decisions.",phase:"Phase",steps:[["Understand","We listen to your organization’s context, objectives and specific risks."],["Coordinate","We integrate the right technical and territorial capabilities for each project."],["Resolve","We deliver actionable conclusions, clear documentation and close follow-up."]]},pt:{label:"NOSSO MÉTODO",title:"Clareza em cada etapa.",intro:"Um processo comum mantém a conversa focada e transforma complexidade em decisões concretas.",phase:"Fase",steps:[["Compreender","Ouvimos o contexto, os objetivos e os riscos específicos da sua organização."],["Coordenar","Integramos as capacidades técnicas e territoriais adequadas para cada projeto."],["Resolver","Entregamos conclusões acionáveis, documentação clara e acompanhamento próximo."]]}}[locale];const images=["/images/meeting.jpg","/images/office.jpg","/images/finance.jpg"];return <section className="local-method" id="metodo"><div className="local-method-heading"><p className="section-label">{text.label}</p><h2>{text.title}</h2><p>{text.intro}</p></div><div className="method-steps">{text.steps.map((s,i)=><article key={s[0]}><img src={images[i]} alt=""/><div><span>{text.phase}</span><h3>{s[0]}</h3><p>{s[1]}</p></div></article>)}</div></section>}
function LocalIndustries({locale}:{locale:Locale}){const text={es:{label:"EXPERIENCIA SECTORIAL",title:"Conocimiento que entiende su negocio.",action:"Explorar enfoque",sectors:[["Empresas familiares","Gobierno, control y continuidad para organizaciones que construyen legado."],["Manufactura y distribución","Procesos, costos y cumplimiento para operaciones que necesitan avanzar con precisión."],["Servicios y tecnología","Información confiable y estructuras preparadas para nuevos modelos de negocio."],["Operaciones regionales","Coordinación entre mercados para empresas con presencia o expansión internacional."]]},en:{label:"INDUSTRY EXPERIENCE",title:"Knowledge that understands your business.",action:"Explore approach",sectors:[["Family businesses","Governance, control and continuity for organizations building a legacy."],["Manufacturing and distribution","Processes, costs and compliance for operations that need to move forward precisely."],["Services and technology","Reliable information and structures ready for new business models."],["Regional operations","Cross-market coordination for companies with an international presence or expansion plans."]]},pt:{label:"EXPERIÊNCIA SETORIAL",title:"Conhecimento que entende seu negócio.",action:"Explorar abordagem",sectors:[["Empresas familiares","Governança, controle e continuidade para organizações que constroem legado."],["Manufatura e distribuição","Processos, custos e compliance para operações que precisam avançar com precisão."],["Serviços e tecnologia","Informações confiáveis e estruturas preparadas para novos modelos de negócio."],["Operações regionais","Coordenação entre mercados para empresas com presença ou expansão internacional."]]}}[locale];return <section className="local-industries"><div><p className="section-label">{text.label}</p><h2>{text.title}</h2></div><div className="industry-grid">{text.sectors.map(s=><article key={s[0]}><h3>{s[0]}</h3><p>{s[1]}</p><span>{text.action} ↗</span></article>)}</div></section>}

export function LocalPage({site,locale,onPage}:{site:"mexico"|"salvador",locale:Locale,onPage:(p:PageKey)=>void}){const d=localSites[site];const lt=site==="mexico"?localTranslations.mexico:localTranslations.paraguay;const practiceImages=["/images/practices/audit.jpg","/images/practices/tax.jpg","/images/practices/consulting.jpg","/images/practices/trade.jpg"];const descriptions={es:["Revisión independiente de información financiera, controles y obligaciones bajo estándares profesionales.","Planeación responsable y cumplimiento oportuno para reducir contingencias.","Información clara, procesos eficientes y acompañamiento para decisiones estratégicas.","Cumplimiento aduanero y soporte para operaciones de comercio internacional."],en:["Independent review of financial information, controls and obligations under professional standards.","Responsible planning and timely compliance to reduce contingencies.","Clear information, efficient processes and support for strategic decisions.","Customs compliance and support for international trade operations."],pt:["Revisão independente de informações financeiras, controles e obrigações sob padrões profissionais.","Planejamento responsável e compliance oportuno para reduzir contingências.","Informações claras, processos eficientes e apoio para decisões estratégicas.","Compliance aduaneiro e suporte para operações de comércio internacional."]}[locale];const localLabels={es:{cap:"CAPACIDADES",team:"NUESTRO EQUIPO"},en:{cap:"CAPABILITIES",team:"OUR TEAM"},pt:{cap:"CAPACIDADES",team:"NOSSA EQUIPE"}}[locale];return <><section className="local-hero"><div><p className="section-label">{lt.slogan[locale]}</p><h1>{lt.hero[locale]}</h1><p>{lt.intro[locale]}</p><a href="#contacto">{lt.contactTitle[locale]} <span>↗</span></a></div><img src={d.image} alt=""/></section><section className="local-firm" id="firma"><div><p className="section-label">AUDITAXES {lt.country[locale].toUpperCase()}</p><h2>{lt.firmTitle[locale]}</h2></div><div><p>{lt.firmBody[locale]}</p><img src="/images/finance.jpg" alt=""/></div></section><LocalMethod locale={locale}/><section className="practice-area" id="capacidades"><p className="section-label">{localLabels.cap}</p><h2>{lt.practiceTitle[locale]}</h2><div>{lt.practices[locale].map((p,i)=><article key={p}><img className="practice-photo" src={practiceImages[i]} alt=""/><h3>{p}</h3><p>{descriptions[i]}</p></article>)}</div></section><LocalIndustries locale={locale}/><section className="partners" id="equipo"><div><p className="section-label">{localLabels.team}</p><h2>{lt.partnersTitle[locale]}</h2><p>{lt.partnersBody[locale]}</p></div><div className="partner-grid">{d.partners.map((p,i)=><article key={p.name}><div className="partner-photo"><img src={p.image} alt={p.name}/></div><h3>{p.name}</h3><p>{lt.partners[i].role[locale]}</p></article>)}</div></section><ContactSection locale={locale} details={{email:lt.email,phone:lt.phone,address:lt.address}}/><Footer locale={locale} onPage={onPage}/></>}

